packages:
  - 'frontend'
  - 'backend'
  - 'domain_model'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@5.20260910.0-alpha
  - wrangler@4.131.0

peerDependencyRules:
  ignoreMissing:
    - '@netlify/blobs'
    - '@opentelemetry/api'
    - 'rollup'
  allowAny:
    - '@netlify/blobs'
    - '@opentelemetry/api'
    - 'rollup'
