/// <reference types="astro/client" />
/// <reference types="vite/client" />
/// <reference types="@clerk/astro/types" />
/// <reference path="../worker-configuration.d.ts" />

// ── CSS side-effect imports ────────────────────────────────────────────────
// Vite handles .css files at build time. This declaration silences ts(2882)
// in Astro frontmatter where CSS files are imported for bundling.
declare module '*.css' {}
declare module '*.module.css' {
  const classes: Record<string, string>;
  export default classes;
}

// ---------------------------------------------------------------------------
// Cloudflare Worker runtime environment
// Bindings are generated by `wrangler types` into worker-configuration.d.ts
//
// Astro v6 + @astrojs/cloudflare v13+:
//   - Astro.locals.runtime.env is REMOVED
//   - Use `import { env } from "cloudflare:workers"` for CF bindings
//   - Astro.locals.cfContext replaces locals.runtime.ctx
// ---------------------------------------------------------------------------

/** Minimal Cloudflare Fetcher / Service-binding interface. */
interface CloudflareServiceBinding {
  fetch(request: Request): Promise<Response>;
}

/**
 * Augment the auto-generated `Env` with bindings not yet tracked by
 * `wrangler types` (e.g. OCR_SERVICE, which requires the ocr-service to be
 * deployed before `wrangler types` picks it up).
 */
interface Env {
  OCR_SERVICE?: CloudflareServiceBinding;
}

declare module 'cloudflare:workers' {
  export const env: Env;
}

// ── Window extensions used in book.astro <script> blocks ─────────────────────
// Repeated here (also in types/global.d.ts) so the Astro embedded-TS service
// picks them up — it honours env.d.ts but may miss supplementary .d.ts files.
interface Window {
  /**
   * Wizard step gating — set by WizardNavigatorIsland so child islands
   * can enable/disable the "Next" button without direct DOM coupling.
   */
  __wizEnableNext?: (enabled: boolean) => void;
  __maplibreMaps?: Record<string, unknown>;
  showToast?: (icon: string, title: string, message?: string, duration?: number) => void;
  __sectionManager?: any;
  __ipSectionManagers?: any[];
}

// In @astrojs/cloudflare v13+, Runtime only exposes cfContext.
type Runtime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  // Merged with Runtime and Clerk's locals so all bindings are typed correctly.
  interface Locals extends Runtime {
    /** Authenticated user — null when role is 'guest'. */
    user: { id: string; email: string; name: string } | null;
    /** Coarse-grained role: 'admin' set via Clerk publicMetadata.role. */
    role: 'admin' | 'pilgrim' | 'guest';
    locale: string;
    /** Always null — session is managed by Clerk cookies. */
    sessionToken: string | null;
  }
}
